#!/usr/bin/env python

import sys, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we are on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).decode("utf-8").strip()
print(f"prepare-commit-msg: On branch '{branch}'")

# Populate the commit message with the issue num if one exists in branch name
if branch not in ['main','master','dev','develop'] and not branch.startswith("rc/"):
	result = re.match("(.*)/([A-Z0-9]{2,5}-[0-9]{1,4}){0,1}[-_/]*(.*)", branch)
	if not result or not result.group(2):
		print("Note: Branch doesn't have a valid JIRA ticket associated")
		exit()
	issue_number = result.group(2)
	with open(commit_msg_filepath, 'r+') as f:
		content = f.read()
		f.seek(0,0)
		if issue_number not in content:
			print(f"prepare-commit-msg: Adding in JIRA ticket [{issue_number}] to commit message...")
			f.write(f"[{issue_number}] {content}")